# Generated by Django 3.2.15 on 2022-10-21 17:55

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_auto_20150509_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='url_youtube',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Unavailable'), (1, 'Available'), (2, 'Submitted For Review'), (3, 'In Review'), (4, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='peerreview',
            name='review_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='course',
            field=models.ForeignKey(help_text='Cursus waarvoor deze syllabus bestemd is', on_delete=django.db.models.deletion.CASCADE, to='registrar.course'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(help_text='Bedoeld voor PDF format', null=True, upload_to='uploads'),
        ),
    ]
