# Generated by Django 4.1.2 on 2022-12-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_auto_20221021_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=85, null=True, verbose_name='Title')),
            ],
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.assignment'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.exam'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.quiz'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.assignment'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.exam'),
        ),
        migrations.AlterField(
            model_name='truefalsequestion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registrar.quiz'),
        ),
        migrations.CreateModel(
            name='TstCourseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volgnr', models.IntegerField(blank=True, default=1, help_text='Sequece of module in Course', null=True, verbose_name='Serial number')),
                ('section', models.CharField(blank=True, default='pargr.', help_text='Section (number) of module in course', max_length=45, null=True, verbose_name='Section')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.module')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(through='registrar.TstCourseModule', to='registrar.module'),
        ),
    ]
