# Generated by Django 3.2.15 on 2022-12-12 12:03

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0004_module_alter_multiplechoicequestion_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tstcoursemodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_modules', to='registrar.course'),
        ),
        migrations.AlterField(
            model_name='tstcoursemodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_courses', to='registrar.module'),
        ),
        migrations.CreateModel(
            name='TstUnitModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnr', models.IntegerField(blank=True, default=1, help_text='Sequece of unit in module', null=True, verbose_name='Serial number')),
                ('section', models.CharField(blank=True, default='pargr.', help_text='Section (number) of module in course', max_length=45, null=True, verbose_name='Section')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_units', to='registrar.module')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_modules', to='registrar.learningunit')),
            ],
        ),
        migrations.AddField(
            model_name='learningunit',
            name='module',
            field=models.ManyToManyField(blank=True, through='registrar.TstUnitModule', to='registrar.Module'),
        ),
    ]
