# Generated by Django 4.1.2 on 2022-12-19 11:33

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('registrar', '0005_auto_20221212_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='learningunit',
            name='module',
            field=models.ManyToManyField(blank=True, related_name='learningunits', through='registrar.TstUnitModule', to='registrar.module'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(to='account.teacher'),
        ),
    ]
